### ISSUE TITLE
[Console Output] error spam && [Updates] A1111 updates breaking config if after init

### ISSUE THREAD

**Issue by Mr-Firesign** [poipoi300/auto-sd-krita-ext-xl#11]
I keep getting missing requirements messages when generating. I tried searching for what I needed to do online but I couldn't find anything and I don't know how to fix it. It still generates the image, but the image doesn't generate, like it gives the output but it shows up un-generated, I don't know how to describe it. I don't know if it is a stable diffusion problem or a auto-sd-krita problem.

```
sampler_index argument for StableDiffusionProcessing does not do anything; use sampler_name
*** Error running setup: E:\Stable-difusion\Rsd.webui\webui\modules/processing_scripts\refiner.py
    Traceback (most recent call last):
      File "E:\Stable-difusion\Rsd.webui\webui\modules\scripts.py", line 979, in setup_scrips
        script.setup(p, *script_args)
    TypeError: ScriptRefiner.setup() missing 3 required positional arguments: 'enable_refiner', 'refiner_checkpoint', and 'refiner_switch_at'

---
*** Error running setup: E:\Stable-difusion\Rsd.webui\webui\modules/processing_scripts\sampler.py
    Traceback (most recent call last):
      File "E:\Stable-difusion\Rsd.webui\webui\modules\scripts.py", line 979, in setup_scrips
        script.setup(p, *script_args)
    TypeError: ScriptSampler.setup() missing 3 required positional arguments: 'steps', 'sampler_name', and 'scheduler'

---
*** Error running setup: E:\Stable-difusion\Rsd.webui\webui\modules/processing_scripts\seed.py
    Traceback (most recent call last):
      File "E:\Stable-difusion\Rsd.webui\webui\modules\scripts.py", line 979, in setup_scrips
        script.setup(p, *script_args)
    TypeError: ScriptSeed.setup() missing 6 required positional arguments: 'seed', 'seed_checkbox', 'subseed', 'subseed_strength', 'seed_resize_from_w', and 'seed_resize_from_h'

---
*** Error running process: E:\Stable-difusion\Rsd.webui\webui\extensions-builtin\soft-inpainting\scripts\soft_inpainting.py
    Traceback (most recent call last):
      File "E:\Stable-difusion\Rsd.webui\webui\modules\scripts.py", line 825, in process
        script.process(p, *script_args)
    TypeError: Script.process() missing 7 required positional arguments: 'enabled', 'power', 'scale', 'detail_preservation', 'mask_inf', 'dif_thresh', and 'dif_contr'

---
```

![image](https://github.com/poipoi300/auto-sd-krita-ext-xl/assets/140429580/d17cec37-9144-41da-beef-ab9dd863b6ba)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - WebUI commit revision [1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0]
 - Extension commit revision (93245c05fc82c70682663328acdd9edeaae91546)

**Comment by poipoi300** [comment]
First, thanks for opening an issue. I hadn't tested newer versions and I wasn't sure if it was still working.

### Requirements issue 
This is known from the original extension, but I appreciate it being documented here now. 

Unfortunately, you can't fix this yourself without getting into the code and it's low priority for me. There are messages I could easily remove by removing unused arguments but doing so would break compatibly with older versions which do use those arguments. 

How much value is there to keeping compatibility with older versions? I'm not sure, but leaning towards less and less. The messages are annoying for sure though. It might be possible to hide them, but it's not a solution I'm keen on.

### Images showing up un-generated
Do you mean that they don't make it to krita? Like if you hit the generate button, it'll show up in the console, generate normally and get saved in your txt2img folder for instance, then you get an empty layer in krita? Or noise? I know the code to do with that is quite sensitive. If we're lucky it's a simple fix. I'll make that my priority regardless.

**Comment by Mr-Firesign** [comment]
For the images, it showed up as noise, like it was stopping at the first step's generation while continuing to "generate" before outputting a image of random noise. But after restarting/messing with settings it stopped doing that for me. So I guess it was just a me problem. I'm sorry for wasting any of your time.

**Comment by poipoi300** [comment]
Don't worry about wasting time, like I said I appreciate this being here and even if it resolved itself, it's still an issue that exists and it's definitely not just you.

Did you recently update your A1111 repo and it was since then that you've had noisy images? I've noticed sometimes the settings file can be in an incompatible state when updating. This usually fixes itself after restarting both A1111 and krita completely. (Close both, open A1111, open krita). If it doesn't, I would suggest following the last 2 steps in the troubleshooting "others" section of the original wiki [here](https://github.com/Interpause/auto-sd-paint-ext/wiki/Troubleshooting#others). I would also recommend making backups of these files before deleting them since they contain the current settings, including prompts.

**Comment by Mr-Firesign** [comment]
yes, I did just recently update and troubleshoot some problems, I already downgraded setuptools to 69.5.1 from this post [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15863#issuecomment-2126261749.)

Also thanks for the troubleshooting guide. I'll make sure to refer to it if I run into any other problems.

**Comment by poipoi300** [comment]
Definitely an issue that still exists lol, reopening so people can see it and know they're not alone.
